
from django.db import connection

sql_commands = [
    'CREATE TABLE "call_notification" ("id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "message" text NOT NULL, "created_at" timestamptz NOT NULL, "room_id" bigint NOT NULL, "sender_id" bigint NOT NULL, "user_id" bigint NOT NULL);',
    'ALTER TABLE "call_notification" ADD CONSTRAINT "call_notification_room_id_27ad8f60_fk_call_chatroom_id" FOREIGN KEY ("room_id") REFERENCES "call_chatroom" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'ALTER TABLE "call_notification" ADD CONSTRAINT "call_notification_sender_id_54943b11_fk_chess_pyt" FOREIGN KEY ("sender_id") REFERENCES "chess_python_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'ALTER TABLE "call_notification" ADD CONSTRAINT "call_notification_user_id_e768def8_fk_chess_pyt" FOREIGN KEY ("user_id") REFERENCES "chess_python_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'CREATE INDEX "call_notification_room_id_27ad8f60" ON "call_notification" ("room_id");',
    'CREATE INDEX "call_notification_sender_id_54943b11" ON "call_notification" ("sender_id");',
    'CREATE INDEX "call_notification_user_id_e768def8" ON "call_notification" ("user_id");'
]

with connection.cursor() as cursor:
    for sql in sql_commands:
        try:
            cursor.execute(sql)
            print(f"Executed: {sql[:50]}...")
        except Exception as e:
            print(f"Error executing {sql[:50]}: {e}")

print("Done.")
