# Generated by Django 6.0 on 2026-01-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.chatroom'),
        ),
    ]
