# Generated by Django 6.0 on 2026-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_gameinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('from_row', models.IntegerField()),
                ('from_col', models.IntegerField()),
                ('to_row', models.IntegerField()),
                ('to_col', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
