# Generated by Django 6.0 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_gamemove'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='game_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
