# Generated by Django 6.0 on 2026-02-11 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_gamevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
