# Generated by Django 6.0 on 2026-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_uservoiceprofile_reference_audio_voiceresponsecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoiceprofile',
            name='siliconflow_voice_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
