# Generated by Django 6.0 on 2026-03-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0011_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('message', 'Message'), ('invitation', 'Invitation'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
    ]
