# Generated by Django 6.0.2 on 2026-03-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0012_notificationlog_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('message', 'Chat Message'), ('invitation', 'Game Invitation'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('message', 'Chat Message'), ('invitation', 'Game Invitation'), ('system', 'System')], max_length=30)),
                ('is_blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
